# Configure.
environment:
  PATH: C:\%PYTHON%;C:\%PYTHON%\Scripts;%PATH%
  PYTHON: Python37
  matrix:
    - TOX_ENV: py37

# Run.
install:
  - python -m pip install -U pip tox
  - git config --global user.email "builds@appveyor.com"
  - git config --global user.name "AppVeyor"
build_script: pip install -r requirements.txt
test_script: tox
