..  |author|    replace:: Roie R. Black
..  |author-email|   replace:: roie.black@gmail.com
..  |pylit|     replace:: PyLiT
..  |DRY|       replace:: *Don't repeat Yourself*
..  |TDD|       replace:: *Test Driven Development*
..	|ACC|		replace:: Austin Community College
..	_ACC:		https://www.austincc.edu/rblack
..	|AFIT|		replace:: Air Force Institute of Tecnology
..	_AFIT:		https://www.afit.edu/
..  _Antlr:     https://www.antlr.org/
..  _Appveyor:  https://www.appveyor.com/
..  _CodeClimate:    https://codeclimate.com/quality/
..  _docutils:  https://docutils.sourceforge.io/
..  _Jinja2:    https://jinja.palletsprojects.com/en/2.11.x/
..	_LaTeX:		https://www.latex-project.org/
..	|LP|		replace:: *Literate Programming*
..	_LP:		https://en.wikipedia.org/wiki/Literate_programming
..  _Make:      https://www.gnu.org/software/make/
..  _MyPy:      http://mypy-lang.org/
..  _MonkeyType:    https://github.com/Instagram/MonkeyType
..  _PyPi:      https://pypi.org/
..  _pytest:    https://docs.pytest.org/en/latest/
..  _pytest-cov:    https://github.com/pytest-dev/pytest-cov/
..	|RST|		replace:: reStructuredText
..	_RST:		https://www.sphinx-doc.org/en/master/usage/restructuredtext/
..	_Sphinx:	http://sphinx-doc.org/
..	_TeX:		https://en.wikipedia.org/wiki/TeX
..	_Git:		https://git-scm.com/
..	_GitHub:	https://github.com/
..  _Travis-CI: https://travis-ci.org/
..  _Tox:       https://github.com/tox-dev/tox
..  _Minimal Structure: https://python-packaging.readthedocs.io/en/latest/minimal.html
