..	|ACC|		replace:: Austin Community College
..	_ACC:		https://www.austincc.edu/rblack
..	|AFIT|		replace:: Air Force Institute of Tecnology
..	_AFIT:		https://www.afit.edu/
..  _Antlr:     https://www.antlr.org/
..	_LaTeX:		https://www.latex-project.org/
..	|LP|		replace:: *Literate Programming*
..	_LP:		https://en.wikipedia.org/wiki/Literate_programming
..  _Make:      https://www.gnu.org/software/make/
..  _PyPi:      https://pypi.org/
..  _pytest:    https://docs.pytest.org/en/latest/
..	|RST|		replace:: reStructuredText
..	_RST:		https://www.sphinx-doc.org/en/master/usage/restructuredtext/
..	_Sphinx:	http://sphinx-doc.org/
..	_TeX:		https://en.wikipedia.org/wiki/TeX
..	_Git:		https://git-scm.com/
..	_GitHub:	https://github.com/
..  _Travis-CI: https://travis-ci.org/

..  _Minimal Structure: https://python-packaging.readthedocs.io/en/latest/minimal.html
